version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew test
reports:
  test-reports:
    files:
      - app/build/test-results/testDebugUnitTest/*.xml
    file-format: JUNITXML
