version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
artifacts:
  files:
    - app/build/outputs/apk/release/app-release-unsigned.apk
  name: app-release-unsigned.apk
  discard-paths: yes
